- name: Reboot now (inline)
  when:
    - sccm_allow_reboot | bool
    - sccm_pending_reboot | bool
  ansible.windows.win_reboot:
    msg: "Rebooting to complete SCCM updates (Autopilot)."
    pre_reboot_delay: 15
    reboot_timeout: 3600

- name: Wait after reboot (settle)
  ansible.builtin.pause:
    seconds: "{{ sccm_wait_after_reboot }}"
  when:
    - sccm_allow_reboot | bool
    - sccm_pending_reboot | bool
